export const AUTH_ACCESS_TOKEN_COOKIE_NAME = 'accessToken';
export const AUTH_REFRESH_TOKEN_COOKIE_NAME = 'refreshToken';

export const AUTH_ACCESS_TOKEN_TTL_SECONDS = 15 * 60;
export const AUTH_REFRESH_TOKEN_TTL_SECONDS = 30 * 24 * 60 * 60;

export const AUTH_ACCESS_TOKEN_COOKIE_MAX_AGE_MS =
  AUTH_ACCESS_TOKEN_TTL_SECONDS * 1000;
export const AUTH_REFRESH_TOKEN_COOKIE_MAX_AGE_MS =
  AUTH_REFRESH_TOKEN_TTL_SECONDS * 1000;

export const AUTH_ACCESS_TOKEN_COOKIE_PATH = '/api';
export const AUTH_REFRESH_TOKEN_COOKIE_PATH = '/api/auth/refresh';
